INSERT INTO STUDENT(ID, NAME, SURNAME) VALUES(1, 'Student Name1', 'Surname1');
INSERT INTO STUDENT(ID, NAME, SURNAME) VALUES(2, 'Student Name2', 'Surname2');
INSERT INTO STUDENT(ID, NAME, SURNAME) VALUES(3, 'Student Name3', 'Surname3');